// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvpjsittuozquoehqwvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2cGpzaXR0dW96cXVvZWhxd3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTkyNjksImV4cCI6MjA2MDM5NTI2OX0.iEmfDbQQGsm6aWl1etecpySmLP6kA78VuHI6u8fMgRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);